# Level 3
name: GitHub Actions MLops Lab 1 Level 3
on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  Test Docker Login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  # Docker Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
  #     # - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     # - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/mlops-lab1:latest
